@startuml
'https://plantuml.com/class-diagram
class Main{
    +String name
    +int price
    +int quantity

    +main()
}

class ReadFile{
    +read()
}

class SearchFile{
    -String name
    +search()
}
Main --o ReadFile
Main --o SearchFile
@enduml