@startuml
'https://plantuml.com/class-diagram
class Solution45{
    +String text
    +main()

}

class ModifyFile{
    +String text
    -modify()
}

class CreateFile{
    +String newText
    -create()
    -write()
}

Solution45 <-- CreateFile
ModifyFile --> CreateFile

@enduml